name: Bug report
description: Create a report to help us improve

assignees: [""]
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.

        Please fill in as much of the template below as you're able.

        ---
  - type: input
    id: title
    attributes:
      label: Title
      description: A clear and concise description of what the bug is.
      placeholder: What is the bug?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: How can we reproduce the behavior?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please complete the following information.
      placeholder: What is your environment?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Anything else we should know?
    validations:
      required: false
