name: Documentation request
description: Suggest an idea for this project to improve documentation

assignees: [""]
labels:
  - "documentation"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a documentation improvement.

        Please fill in as much of the template below as you're able.

        ---
  - type: input
    id: title
    attributes:
      label: Title
      description: A clear and concise description of what the documentation improvement is.
      placeholder: What is the documentation improvement?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the documentation improvement is.
      placeholder: Describe the documentation improvement
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why is this documentation improvement important to you?
      placeholder: Why is this documentation improvement important to you?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any other context?
    validations:
      required: false
