name: Generate terraform docs

on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          working-dir: ./src/module-example-1,./src/module-example-1/model,./src/module-example-1/wrapper,./src/module-example-1/examples/complete
          output-file: README.md
          output-method: inject
          git-push: "true"
